name: Slack Notifications

on:
  workflow_dispatch: {}                # ← Actions 탭에서 수동 실행
  push:
    branches: ["main", "develop"]      # develop에서도 테스트
  pull_request:
    types: [opened, synchronize, closed]
    branches: ["main", "develop"]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify for push
        if: github.event_name == 'push'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "blocks": [
                { "type": "section",
                  "text": { "type": "mrkdwn",
                    "text": ":inbox_tray: *PUSH* to *${{ github.ref_name }}* in *${{ github.repository }}*" } },
                { "type": "section",
                  "fields": [
                    { "type": "mrkdwn", "text": "*Actor:*\n${{ github.actor }}" },
                    { "type": "mrkdwn", "text": "*Message:*\n${{ github.event.head_commit.message }}" }
                  ]},
                { "type": "actions", "elements": [
                  { "type": "button", "text": { "type": "plain_text", "text": "Commit" },
                    "url": "${{ github.event.head_commit.url }}" }
                ]}
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: C09CZPMC6VC   # ← 채널 ID 직접 사용해도 됨

      - name: Notify for PR
        if: github.event_name == 'pull_request'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "blocks": [
                { "type": "section",
                  "text": { "type": "mrkdwn",
                    "text": ":bell: *PR* ${{ github.event.action }} → *${{ github.base_ref }}*\n*${{ github.event.pull_request.title }}*" } },
                { "type": "actions", "elements": [
                  { "type": "button", "text": { "type": "plain_text", "text": "Open PR" },
                    "url": "${{ github.event.pull_request.html_url }}" }
                ]}
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: C09CZPMC6VC
